Repository UKHomeOffice/hocs-audit, pull requests merged in 2022-04, with the labels that each got.

#205 HOCS-4940: Create an empty table partition scheme
  src/main/resources/db/migration/postgresql/V1_6__CREATE_TABLE_AUDIT_EVENTS.sql
Labels: patch

#211 HOCS-4863: update semver tag action release version
  .github/workflows/pr-check.yml
  .github/workflows/semver.yml
Labels: skip-release

#206 HOCS-4940: Point the service at the new table
  src/main/java/uk/gov/digital/ho/hocs/audit/AuditEventResource.java
  src/main/java/uk/gov/digital/ho/hocs/audit/AuditEventService.java
  src/main/java/uk/gov/digital/ho/hocs/audit/CaseAuditEventResource.java
  src/main/java/uk/gov/digital/ho/hocs/audit/auditdetails/dto/CreateAuditResponse.java
  src/main/java/uk/gov/digital/ho/hocs/audit/auditdetails/dto/GetAuditListResponse.java
  src/main/java/uk/gov/digital/ho/hocs/audit/auditdetails/dto/GetAuditListSummaryResponse.java
  src/main/java/uk/gov/digital/ho/hocs/audit/auditdetails/dto/GetAuditResponse.java
  src/main/java/uk/gov/digital/ho/hocs/audit/auditdetails/dto/GetAuditSummaryResponse.java
  src/main/java/uk/gov/digital/ho/hocs/audit/auditdetails/model/AuditEvent.java
  src/main/java/uk/gov/digital/ho/hocs/audit/auditdetails/repository/AuditRepository.java
  src/main/java/uk/gov/digital/ho/hocs/audit/aws/listeners/AuditListener.java
  src/main/java/uk/gov/digital/ho/hocs/audit/export/ExportService.java
  src/main/java/uk/gov/digital/ho/hocs/audit/export/parsers/AbstractDataParser.java
  src/main/java/uk/gov/digital/ho/hocs/audit/export/parsers/interests/AbstractInterestDataParser.java
  src/test/java/uk/gov/digital/ho/hocs/audit/AuditDataServiceTest.java
  src/test/java/uk/gov/digital/ho/hocs/audit/AuditResourceTest.java
  src/test/java/uk/gov/digital/ho/hocs/audit/AuditServiceCreateTest.java
  src/test/java/uk/gov/digital/ho/hocs/audit/AuditServiceGetTest.java
  src/test/java/uk/gov/digital/ho/hocs/audit/auditdetails/model/AuditDataTest.java
  src/test/java/uk/gov/digital/ho/hocs/audit/auditdetails/repository/AuditRepositoryTest.java
  src/test/java/uk/gov/digital/ho/hocs/audit/aws/listeners/AuditListenerTest.java
  src/test/java/uk/gov/digital/ho/hocs/audit/aws/listeners/integration/CreateAuditTest.java
  src/test/java/uk/gov/digital/ho/hocs/audit/export/AuditExportServiceTest.java
  src/test/java/uk/gov/digital/ho/hocs/audit/export/CaseNoteExportTest.java
  src/test/java/uk/gov/digital/ho/hocs/audit/export/parsers/interests/BfInterestDataParserTest.java
  src/test/java/uk/gov/digital/ho/hocs/audit/export/parsers/interests/FoiInterestDataParserTest.java
  src/test/resources/export/afterTest.sql
  src/test/resources/export/beforeTest.sql
Labels: patch

#212 HOCS-4940: remove log spam
  src/main/java/uk/gov/digital/ho/hocs/audit/AuditEventService.java
Labels: patch

#207 HOCS-4940: Remove (but retain) *_viewed messages
  src/main/resources/db/migration/postgresql/V1_7__DETACH_OLD_VEIWED_PARTITIONS.sql
Labels: patch

#208 HOCS-4940: Remove Query_Hints
  src/main/java/uk/gov/digital/ho/hocs/audit/auditdetails/repository/AuditRepository.java
  src/main/java/uk/gov/digital/ho/hocs/audit/auditdetails/repository/AuditRepositoryImpl.java
Labels: patch

#215 HOCS-4940: Update Index to match prod after incident
  src/main/resources/db/migration/postgresql/V1_8__REPLACE_EXTRACT_INDEX.sql
Labels: patch

#220 HOCS-4940: add latest triggers
  src/main/resources/db/migration/postgresql/V1_10__CREATE_LATEST_TABLE_TRIGGERS.sql
Labels: patch

#221 HOCS-4940: use latest table
  src/main/java/uk/gov/digital/ho/hocs/audit/export/ExportService.java
  src/test/java/uk/gov/digital/ho/hocs/audit/export/AuditExportServiceTest.java
Labels: minor

#230 HOCS-4980: Fix Audit message spelling and service running in try/catch
  src/main/java/uk/gov/digital/ho/hocs/audit/AuditEventService.java
  src/main/java/uk/gov/digital/ho/hocs/audit/HocsAuditApplication.java
  src/main/java/uk/gov/digital/ho/hocs/audit/application/LogEvent.java
Labels: patch

#224 Remove db initialise initcontainer
  kube/kd/deployment.yaml
Labels: patch

#226 HOCS-4921: ~half the execution time for audit_event_latest_events query
  src/main/java/uk/gov/digital/ho/hocs/audit/auditdetails/repository/AuditRepositoryLatestEvents.java
Labels: patch

#227 HOCS-4921: Reduce 2/3rds execution time for auditByCaseUUIDAndTypesIn query
  src/main/java/uk/gov/digital/ho/hocs/audit/auditdetails/repository/AuditRepository.java
Labels: patch

#228 HOCS-4921: 1/6th execution time for auditByCaseUUIDAndTypesInFromDate query
  src/main/java/uk/gov/digital/ho/hocs/audit/AuditEventService.java
  src/main/java/uk/gov/digital/ho/hocs/audit/CaseAuditEventResource.java
  src/main/java/uk/gov/digital/ho/hocs/audit/auditdetails/repository/AuditRepository.java
  src/test/java/uk/gov/digital/ho/hocs/audit/AuditServiceGetTest.java
Labels: minor

#234 HOCS-4980: remove GSON usage
  build.gradle
  src/main/java/uk/gov/digital/ho/hocs/audit/core/config/GsonConfiguration.java
  src/main/java/uk/gov/digital/ho/hocs/audit/core/utils/JsonValidator.java
  src/main/java/uk/gov/digital/ho/hocs/audit/entrypoint/AuditListener.java
  src/main/java/uk/gov/digital/ho/hocs/audit/entrypoint/dto/CreateAuditDto.java
  src/main/java/uk/gov/digital/ho/hocs/audit/service/AuditEventService.java
  src/test/java/uk/gov/digital/ho/hocs/audit/entrypoint/AuditListenerTest.java
  src/test/java/uk/gov/digital/ho/hocs/audit/entrypoint/integration/CreateAuditTest.java
  src/test/java/uk/gov/digital/ho/hocs/audit/service/AuditEventServiceTest.java
Labels: minor

#235 HOCS-4120 Reduce Debug and Info logging around the Clients.
  src/main/java/uk/gov/digital/ho/hocs/audit/client/casework/CaseworkClient.java
  src/main/java/uk/gov/digital/ho/hocs/audit/client/info/InfoClient.java
  src/main/java/uk/gov/digital/ho/hocs/audit/core/LogEvent.java
  src/main/java/uk/gov/digital/ho/hocs/audit/core/RestHelper.java
  src/main/java/uk/gov/digital/ho/hocs/audit/core/exception/RestResponseEntityExceptionHandler.java
  src/main/java/uk/gov/digital/ho/hocs/audit/entrypoint/CaseAuditEventResource.java
  src/main/java/uk/gov/digital/ho/hocs/audit/repository/entity/AuditEvent.java
  src/main/resources/logback-spring.xml
  src/test/java/uk/gov/digital/ho/hocs/audit/client/info/InfoClientTest.java
Labels: patch

#236 HOCS-4120: Fix DCU_BUSINESS bug
  src/main/java/uk/gov/digital/ho/hocs/audit/client/casework/CaseworkClient.java
  src/main/java/uk/gov/digital/ho/hocs/audit/client/info/InfoClient.java
  src/main/java/uk/gov/digital/ho/hocs/audit/core/RestHelper.java
  src/test/java/uk/gov/digital/ho/hocs/audit/client/info/InfoClientTest.java
Labels: patch

#241 HOCS-4980: replace 100k casework-service calls with one call to the d…
  src/main/java/uk/gov/digital/ho/hocs/audit/client/casework/CaseworkClient.java
  src/main/java/uk/gov/digital/ho/hocs/audit/repository/AuditRepositoryLatestEvents.java
  src/main/java/uk/gov/digital/ho/hocs/audit/repository/entity/CaseReference.java
  src/main/java/uk/gov/digital/ho/hocs/audit/service/AllocationExportService.java
  src/main/java/uk/gov/digital/ho/hocs/audit/service/AppealExportService.java
  src/main/java/uk/gov/digital/ho/hocs/audit/service/CaseDataExportService.java
  src/main/java/uk/gov/digital/ho/hocs/audit/service/CaseNoteExportService.java
  src/main/java/uk/gov/digital/ho/hocs/audit/service/CorrespondentExportService.java
  src/main/java/uk/gov/digital/ho/hocs/audit/service/ExtensionExportService.java
  src/main/java/uk/gov/digital/ho/hocs/audit/service/InterestExportService.java
  src/main/java/uk/gov/digital/ho/hocs/audit/service/SomuExportService.java
  src/main/java/uk/gov/digital/ho/hocs/audit/service/TopicExportService.java
  src/main/java/uk/gov/digital/ho/hocs/audit/service/domain/converter/ExportDataConverter.java
Labels: patch
