Repository UKHomeOffice/hocs-audit, pull requests merged in 2022-03, with the labels that each got.

#181 HOCS-4696: use GitHub SemVer actions
  .drone.yml
  .github/workflows/label-check.yml
  .github/workflows/semver.yml
  LICENSE
  README.md
Labels: major

#182 HOCS-4696: add missing environment variables
  .drone.yml
Labels: patch

#186 HOCS-4696: Override Dependabot lables
  .github/dependabot.yml
Labels: patch

#189 HOCS-4398 add abilityy to export case type BF2 Interest
  src/main/java/uk/gov/digital/ho/hocs/audit/export/parsers/DataParserFactory.java
Labels: minor
