Repository UKHomeOffice/hocs-audit, pull requests merged in 2022-05, with the labels that each got.

#249 HOCS-4120 Remove Event from Debug line
  src/main/java/uk/gov/digital/ho/hocs/audit/core/LogEvent.java
  src/main/java/uk/gov/digital/ho/hocs/audit/service/AuditEventService.java
Labels: patch

#248 Hocs 4980 add index for latest events by case type
  src/main/resources/db/migration/postgresql/V1_11__CREATE_LATEST_EVENTS_INDEX.sql
Labels: patch

#252 HOCS-5027: add dependabot GitHub Action update
  .github/dependabot.yml
Labels: skip-release

#256 HOCS-5038: improve latest stream handling
  src/main/java/uk/gov/digital/ho/hocs/audit/repository/AuditRepository.java
  src/main/java/uk/gov/digital/ho/hocs/audit/service/CaseDataExportService.java
  src/test/java/uk/gov/digital/ho/hocs/audit/service/CaseDataExportServiceTest.java
Labels: patch

#258 Peg match-label-action to version
  .github/workflows/pr-check.yml
  .github/workflows/semver.yml
Labels: skip-release

#260 HOCS-5041 Show case reference in extract instead of uuid
  src/main/java/uk/gov/digital/ho/hocs/audit/service/SomuExportService.java
Labels: patch

#270 Chore: Upgrade drone build image versions
  .drone.yml
Labels: skip-release

#267 HOCS-4995: add suspension export report
  src/main/java/uk/gov/digital/ho/hocs/audit/entrypoint/dto/AuditPayload.java
  src/main/java/uk/gov/digital/ho/hocs/audit/service/SuspensionExportService.java
  src/main/java/uk/gov/digital/ho/hocs/audit/service/domain/ExportType.java
  src/test/java/uk/gov/digital/ho/hocs/audit/service/SuspensionExportServiceTest.java
Labels: minor
