Repository UKHomeOffice/hocs-audit, pull requests merged in 2022-09, with the labels that each got.

#323 HOCS-2141: Use a smaller container for cron job
  kube/kd/refreshDcuAggregatedCasesView.yaml
Labels: patch

#324 HOCS-5557: Correct POGR values in audit
  src/main/resources/config/case-data-fields.json
Labels: patch

#325 HOCS-5553: handle somu type choices
  src/main/java/uk/gov/digital/ho/hocs/audit/client/info/dto/SomuTypeField.java
  src/main/java/uk/gov/digital/ho/hocs/audit/service/SomuExportService.java
Labels: patch

#326 HOCS-2239: Remove redundant certs container
  kube/kd/deployment.yaml
Labels: patch

#328 HOCS-5503: add fields to audit
  src/main/resources/config/case-data-fields.json
Labels: minor

#329 HOCS-4815: Add IEDET assign screen
  src/main/resources/config/case-data-fields.json
Labels: minor

#330 HOCS-4815: Fix case-data-fields.json syntax error
  src/main/resources/config/case-data-fields.json
Labels: patch, smoketest

#333 HOCS-5634 Add date on custom export filenames
  src/main/java/uk/gov/digital/ho/hocs/audit/entrypoint/CustomExportResource.java
  src/main/java/uk/gov/digital/ho/hocs/audit/service/CustomExportService.java
Labels: patch
