Repository UKHomeOffice/hocs-audit, pull requests merged in 2023-03, with the labels that each got.

#406 Migrate codeQl to Sas Actions
  .github/workflows/codeql-analysis.yml
Labels: skip-release

#412 Hocs 5886 complaint details screen changes
  src/main/resources/config/case-data-fields.json
Labels: minor

#410 Chore: Add Partitions for historic cases
  src/main/resources/db/migration/postgresql/V1_16__ADD_HISTORIC_PARTITIONS.sql
Labels: patch

#413 HOCS-5958:Remove DOB, channel and geneder from case data fields
  src/main/resources/config/case-data-fields.json
Labels: minor

#415 Set downscaler weekend settings
  .drone.yml
  helm/hocs-audit.yaml
  helm/hocs-extracts.yaml
Labels: patch
