Repository UKHomeOffice/hocs-audit, pull requests merged in 2023-01, with the labels that each got.

#370 Format logging string to include audit UUID and exception message
  src/main/java/uk/gov/digital/ho/hocs/audit/service/DynamicExportService.java
Labels: patch

#366 HOCS-5728: Add PSU registration to COMP
  src/main/resources/config/case-data-fields.json
Labels: minor

#367 HOCS-5675: COMP PSU add triage complaint screen
  src/main/resources/config/case-data-fields.json
Labels: minor

#371 Add JPA Query and Lock Timeout
  src/main/resources/application.yml
Labels: patch, smoketest

#373 HOCS-6146: move materialised refresh to controller
  src/main/java/uk/gov/digital/ho/hocs/audit/entrypoint/AdminResource.java
  src/main/java/uk/gov/digital/ho/hocs/audit/entrypoint/CustomExportResource.java
Labels: minor

#372 Add JPA Query and Lock Timeout
  src/main/resources/application.yml
Labels: patch, smoketest

#375 Increment chart version following changes to DCU refresh job
  .drone.yml
Labels: patch

#384 Enable the dcu refresh job in dev.
  helm/hocs-audit.yaml
Labels: patch
